export const solutions = [
  {
    id: 'crm',
    number: '01',
    name: 'CRM',
    picker: 'Leads slip through the cracks.',
    title: 'More follow-through. Fewer missed opportunities.',
    problem:
      'A promising lead should never disappear between a spreadsheet, an inbox and a busy day.',
    pains: [
      'Leads live in different spreadsheets and inboxes.',
      'Follow-ups depend on someone remembering.',
      'Nobody can see who owns the next action.',
      'Your sales forecast is an educated guess.',
      'Customer history gets lost when a team member leaves.',
    ],
    chaos: [
      'Missed follow-up',
      'Who owns this lead?',
      'Another spreadsheet',
      'No customer history',
    ],
    solution:
      'One customer workspace. Every conversation, owner and next step visible to the team.',
    dashboard: 'Your customer pipeline',
    tiles: [
      ['New enquiries', 'Assigned'],
      ['Follow-ups', 'Scheduled'],
      ['Customer history', 'Together'],
      ['Sales pipeline', 'Visible'],
    ],
    steps: [
      ['Capture', 'Bring enquiries from your website and channels into one place.'],
      ['Assign', 'Give every opportunity an owner and a clear next action.'],
      ['Follow up', 'Use reminders and shared history to keep conversations moving.'],
      ['Learn', 'See the pipeline clearly and improve the next sales cycle.'],
    ],
    chart: {
      label: 'First response time',
      unit: 'hours',
      before: 12,
      after: 2,
      max: 16,
      without: [12, 13, 11, 14, 12, 12],
      with: [12, 9, 7, 5, 3, 2],
    },
    secondMetric: { label: 'Follow-up coverage', unit: '%', before: 45, after: 90 },
    benefits: [
      [
        'users',
        'Shared customer memory',
        'Keep the full relationship with the business, not one inbox.',
      ],
      [
        'clock',
        'Timely follow-ups',
        'Make the next action visible before the opportunity goes cold.',
      ],
      ['eye', 'Clear ownership', 'Everyone knows who is responsible and what happens next.'],
      ['chart', 'A useful sales picture', 'Plan around pipeline stages and real team activity.'],
    ],
  },
  {
    id: 'erp',
    number: '02',
    name: 'ERP / SAP',
    picker: 'Teams work from different numbers.',
    title: 'One business. One version of the truth.',
    problem:
      'Operations slow down when finance, purchasing and people are working from different information.',
    pains: [
      'Finance and operations reports never quite match.',
      'The same data is entered into several tools.',
      'Approvals wait in email threads.',
      'Month-end reporting means days of manual checks.',
      'An existing ERP or SAP environment feels disconnected.',
    ],
    chaos: ['Invoice mismatch', 'Approval waiting', 'Duplicate entry', 'Which report is right?'],
    solution:
      'Connect your operating workflows with an ERP workspace or integrations around your existing SAP environment.',
    dashboard: 'Your operations overview',
    tiles: [
      ['Purchasing', 'Approved'],
      ['Finance', 'Reconciled'],
      ['People', 'Connected'],
      ['Reporting', 'Current'],
    ],
    steps: [
      ['Map', 'Understand your departments, approvals and existing ERP/SAP setup.'],
      ['Connect', 'Link the records and systems that need to agree.'],
      ['Automate', 'Route everyday approvals and remove repeated manual entry.'],
      ['Review', 'Give each role a clear view of the decisions they need to make.'],
    ],
    chart: {
      label: 'Daily report preparation',
      unit: 'minutes',
      before: 60,
      after: 15,
      max: 80,
      without: [60, 65, 58, 70, 63, 60],
      with: [60, 48, 35, 26, 20, 15],
    },
    secondMetric: { label: 'Repeated data entry / week', unit: 'hours', before: 12, after: 3 },
    benefits: [
      ['layers', 'Connected departments', 'Give teams access to consistent operational records.'],
      ['check', 'Traceable approvals', 'See where a request is, who owns it and what changed.'],
      [
        'clock',
        'Less repeated work',
        'Let a record move through the workflow without retyping it.',
      ],
      [
        'chart',
        'Clearer reporting',
        'Spend more time on decisions and less on assembling reports.',
      ],
    ],
  },
  {
    id: 'inventory',
    number: '03',
    name: 'Inventory Management',
    picker: 'Stock on paper differs from the shelf.',
    title: 'Know what is in stock. Before you promise it.',
    problem:
      'A sale, a purchase and a stock count should tell the same story, wherever your goods are stored.',
    pains: [
      'Stock records do not match the warehouse.',
      'Fast-moving items run out without warning.',
      'Slow-moving stock ties up working space.',
      'Orders are promised before availability is checked.',
      'Transfers between locations are difficult to trace.',
    ],
    chaos: ['Out of stock', 'Untracked transfer', 'Count mismatch', 'Reorder too late'],
    solution:
      'Bring stock movements, availability and reorder decisions into one inventory workspace.',
    dashboard: 'Your stock overview',
    tiles: [
      ['Stock levels', 'Visible'],
      ['Reorder alerts', 'Ready'],
      ['Locations', 'Linked'],
      ['Movement history', 'Tracked'],
    ],
    steps: [
      ['Record', 'Bring products, locations and opening stock into a clear catalog.'],
      ['Track', 'Log receiving, sales, returns and transfers as they happen.'],
      ['Replenish', 'Use agreed thresholds to flag what needs attention.'],
      ['Reconcile', 'Compare counts with records and review every movement.'],
    ],
    chart: {
      label: 'Stock record accuracy',
      unit: '%',
      before: 82,
      after: 98,
      max: 100,
      without: [82, 80, 84, 79, 81, 82],
      with: [82, 86, 90, 94, 96, 98],
    },
    secondMetric: { label: 'Stock check time', unit: 'minutes', before: 30, after: 5 },
    benefits: [
      ['boxes', 'Visible availability', 'Know what can be sold across your locations.'],
      ['bell', 'Earlier reorder signals', 'Spot low stock before it interrupts a customer order.'],
      ['eye', 'Movement traceability', 'Understand where goods went and why counts changed.'],
      ['layers', 'Connected orders', 'Keep purchasing, sales and inventory working together.'],
    ],
  },
  {
    id: 'web',
    number: '04',
    name: 'Website / Custom software',
    picker: 'Your website creates more manual work.',
    title: 'A digital front door that moves work forward.',
    problem:
      'Your website and software should help customers take the next step and help your team deliver it.',
    pains: [
      'Visitors cannot quickly understand what you offer.',
      'Enquiries arrive without the details your team needs.',
      'Mobile visitors struggle with a slow or confusing journey.',
      'Staff copy orders and requests into another system.',
      'Generic software forces your team into awkward workarounds.',
    ],
    chaos: ['Unclear enquiry', 'Slow mobile page', 'Copy-paste order', 'Another workaround'],
    solution:
      'A clear, fast website and purpose-built software connected to the way your business actually works.',
    dashboard: 'Your digital workflow',
    tiles: [
      ['Website enquiries', 'Captured'],
      ['Customer journey', 'Clear'],
      ['Team workflow', 'Connected'],
      ['Performance', 'Monitored'],
    ],
    steps: [
      ['Understand', 'Identify the visitor task and the business workflow behind it.'],
      ['Design', 'Make the next action clear on every screen size.'],
      ['Build', 'Connect enquiries, orders and tasks to your operating tools.'],
      ['Improve', 'Measure the journey and refine what helps people complete it.'],
    ],
    chart: {
      label: 'Enquiry conversion rate',
      unit: '%',
      before: 1,
      after: 3,
      max: 4,
      without: [1, 1.2, 0.9, 1.1, 1, 1],
      with: [1, 1.4, 1.8, 2.3, 2.7, 3],
    },
    secondMetric: { label: 'Manual request processing', unit: 'minutes', before: 25, after: 8 },
    benefits: [
      [
        'globe',
        'A clearer first impression',
        'Help the right customer understand and act on your offer.',
      ],
      ['users', 'A simpler mobile journey', 'Make important tasks comfortable on smaller screens.'],
      ['layers', 'Software that fits', 'Shape the tools around the workflow your team needs.'],
      ['chart', 'Room to improve', 'Use meaningful journey signals to guide future changes.'],
    ],
  },
]
